title: Data Analysis Portfolio
logo: /assets/img/profilepic.png
description: Data Analysis Portfolio showcasing my expertise in actionable insights and data-driven solutions.

author: Francisco Javier Solórzano Ladrón de Guevara
email: fco.javierslg@gmail.com

theme: jekyll-theme-leap-day

# Footer
footer: |
  Explore my work on GitHub: [Frankenslg](https://github.com/Frankenslg)  
  Connect on LinkedIn: [Francisco Solórzano](https://www.linkedin.com/in/franciscosolorzano-dataanalyst/)  
  Contact: fco.javierslg@gmail.com
