title: Data Analysis Portfolio
logo: /assets/img/profilepic.png
description: A collection of data-driven projects and insights.

author: Francisco Javier Solórzano Ladrón de Guevara
email: fco.javierslg@gmail.com

theme: jekyll-theme-architect

# Links
social_links:
  GitHub: https://github.com/Frankenslg
  LinkedIn: https://www.linkedin.com/in/franciscosolorzano-dataanalyst/

# Footer
footer: |
  Francisco Javier Solórzano Ladrón de Guevara  
  Data Analyst | Contact: fco.javierslg@gmail.com  
  GitHub: [Frankenslg](https://github.com/Frankenslg)  
  LinkedIn: [Francisco Solórzano](https://www.linkedin.com/in/franciscosolorzano-dataanalyst/)
