title: Data Analysis Portfolio
logo: /assets/img/profilepic.png
description: Discover projects and insights that turn data into impactful solutions.

author: Francisco Javier Solórzano Ladrón de Guevara
email: fco.javierslg@gmail.com

theme: merlot-jekyll-theme


