title: Data Analysis Portfolio
logo: /assets/img/profilepic.png
description: Welcome to my Data Analysis Portfolio! Explore my work on actionable insights.

author: Francisco Javier Solórzano Ladrón de Guevara
email: fco.javierslg@gmail.com

theme: jekyll-theme-cayman

# Social Links
social_links:
  GitHub: https://github.com/Frankenslg
  LinkedIn: https://www.linkedin.com/in/franciscosolorzano-dataanalyst/
